import { GoogleGenAI } from "@google/genai";
import { ThumbnailStyle } from "../types";

const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

// Helper to remove the data:image/xyz;base64, part
const extractBase64 = (dataUrl: string): string => {
  return dataUrl.split(',')[1];
};

export const generateThumbnailBackground = async (
  imageBase64: string,
  style: ThumbnailStyle,
  enhanceLighting: boolean
): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is missing");
  }

  const base64Data = extractBase64(imageBase64);
  
  // Specific visual cues for each style to guide the AI better
  let styleDetails = "";
  switch (style) {
    case ThumbnailStyle.LUXURY_SHOWROOM:
      styleDetails = "a dark, high-end luxury showroom with glossy marble floors, spotlights reflecting off the car, and a sleek architectural background. Premium atmosphere.";
      break;
    case ThumbnailStyle.NEON_CITY:
      styleDetails = "a cyberpunk city street at night, wet asphalt with neon blue and purple light reflections, futuristic buildings in the background. High contrast.";
      break;
    case ThumbnailStyle.EPIC_MOUNTAIN:
      styleDetails = "a dramatic mountain pass at golden hour (sunset), epic clouds, lens flare, and a sense of adventure. Cinematic landscape.";
      break;
    case ThumbnailStyle.SPEED_MOTION:
      styleDetails = "a high-speed highway blur effect. The background should be motion-blurred to indicate extreme speed, while the car remains razor sharp. Dynamic angle.";
      break;
    case ThumbnailStyle.MINIMALIST_STUDIO:
      styleDetails = "a void-like matte black studio environment. Strong rim lighting (silhouette effect) outlining the car's curves. moody and mysterious.";
      break;
    default:
      styleDetails = "a professional studio background.";
  }
  
  const prompt = `
    Create a viral, high-CTR YouTube thumbnail image featuring this car.
    
    TASK:
    1. Cut out the car from the original image and compositing it perfectly into: ${styleDetails}
    2. COMPOSITION: Ensure the car is the absolute main focus, taking up 60-70% of the frame, positioned centrally or slightly off-center to allow space for text overlays.
    3. LIGHTING: ${enhanceLighting ? 'Apply aggressive "YouTube Style" lighting: high contrast, rim lighting to separate car from background, and boosted saturation.' : 'Use professional, balanced studio lighting with realistic reflections and soft shadows.'}
    4. REALISM: The car must look 100% integrated into the scene. Match reflections on the car body to the environment.
    5. QUALITY: Automotive magazine photography style, 8k resolution, incredibly sharp details on the vehicle, subtle depth of field on the background.
    
    The final image must look like a premium automotive advertisement.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg', // Assuming jpeg/png, API is flexible
              data: base64Data
            }
          },
          {
            text: prompt
          }
        ]
      }
    });

    // Iterate through parts to find the image
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          return `data:image/png;base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by Gemini.");
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};

export const generateMarketingContent = async (
  carDetails: string,
  carLink: string
): Promise<{ summary: string; script: string }> => {
  if (!apiKey) {
    throw new Error("API Key is missing");
  }

  const prompt = `
    You are a viral marketing expert for "4F Motors", a premium used car dealership.
    I will provide car details. You need to generate two things in Portuguese (Brazil):
    
    1. **YouTube Summary**: 
       - Create a SHORT, PUNCHY, and HIGH-IMPACT summary (max 3 sentences).
       - Focus strictly on the "Wow" factor and urgency.
       - Make it sound like a viral video description.
       - Use fire/rocket emojis to grab attention, but keep text short.
    
    2. **Commercial Script (Roteiro)**: A spoken-word script for a video presenter.
       - **CRITICAL:** DO NOT use any asterisks (**), bolding, italics, or markdown formatting. Write strictly in plain text suitable for a teleprompter.
       - Tone: Enthusiastic, confident, and inviting.

    CAR DETAILS:
    ${carDetails}

    OUTPUT FORMAT (JSON):
    {
      "summary": "The short viral paragraph...",
      "script": "The clean text script..."
    }

    SCRIPT STRUCTURE RULES:
    - Start exactly with: "Esse é o [Car Name + Year], um [Category] que entrega [Benefit 1], [Benefit 2] e [Benefit 3]."
    - Middle paragraph: List technical specs (Motor, HP, Transmission) and key features (Multimedia, Wheels, Camera, etc) fluently as if speaking to a friend.
    - End exactly with: "Venha conhecer na 4F Motors, Rua Maria Otília, 225, Vila Regente Feijó, São Paulo."
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: 'application/json'
      }
    });

    const text = response.text;
    if (!text) throw new Error("No text generated");
    
    return JSON.parse(text);
  } catch (error) {
    console.error("Gemini Text Generation Error:", error);
    throw error;
  }
};